### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TLcache'

### ISSUE THREAD

**Issue by DarkLordJack** [xanthics/gw2craft#25]
When running crafting.py this error is printed out and pypy freezes. Reproducible under both Ubuntu 14.04 and Windows.

7228
Start cooking_karma_fast.html
Process Process-36:
Traceback (most recent call last):
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 25
8, in _bootstrap
    self.run()
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 11
4, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\Crafting.py", line 58, in recipeworker
    totals.update(costCraft(subcmd[0],subcmd[1],subcmd[2],subcmd[3],subcmd[4],deepcopy(cList),mytime,xp_to_level))
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 256, in costCraft
    bucket = makeQueuecraft(c_recipes[tier], cList,craftcount,tier,xp_to_level,craftexo)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 426, in makeQueuecraft
    Globals.TLcache.hash = {} # clear the item cache
AttributeError: 'module' object has no attribute 'TLcache'
Start jewelcraft_450.html
Process Process-37:
Traceback (most recent call last):
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 25
8, in _bootstrap
    self.run()
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 11
4, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\Crafting.py", line 60, in recipeworker
    totals.update(costCraft(cmd[0],cmd[1],cmd[2],cmd[3],cmd[4],deepcopy(cList),mytime,xp_to_level))
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 197, in costCraft
    bucket = makeQueuecraft(c_recipes[400], cList,craftcount,tier,xp_to_level,craftexo)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 426, in makeQueuecraft
    Globals.TLcache.hash = {} # clear the item cache
AttributeError: 'module' object has no attribute 'TLcache'
Start huntsman_fast.html
Process Process-38:
Traceback (most recent call last):
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 25
8, in _bootstrap
    self.run()
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 11
4, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\Crafting.py", line 60, in recipeworker
    totals.update(costCraft(cmd[0],cmd[1],cmd[2],cmd[3],cmd[4],deepcopy(cList),mytime,xp_to_level))
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 273, in costCraft
    bucket = makeQueuecraft(c_recipes[tier], cList,craftcount,tier,xp_to_level,craftexo)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 426, in makeQueuecraft
    Globals.TLcache.hash = {} # clear the item cache
AttributeError: 'module' object has no attribute 'TLcache'
Start tailor.html
Process Process-39:
Traceback (most recent call last):
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 25
8, in _bootstrap
    self.run()
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\lib-python\2.7\multiprocessing\process.py", line 11
4, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\Crafting.py", line 60, in recipeworker
    totals.update(costCraft(cmd[0],cmd[1],cmd[2],cmd[3],cmd[4],deepcopy(cList),mytime,xp_to_level))
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 279, in costCraft
    bucket = makeQueuecraft(c_recipes[tier], cList,craftcount,tier,xp_to_level,craftexo)
  File "C:\Users\anthony\Downloads\pypy-2.5.0-win32\pypy-2.5.0-win32\MakeGuide.py", line 426, in makeQueuecraft
    Globals.TLcache.hash = {} # clear the item cache
AttributeError: 'module' object has no attribute 'TLcache'

**Comment by xanthics** [comment]
Odd.  I've updated to my latest code(but it uses boto for AWS interfacing).  Runs just fine on Linux Mint DE.

My pypy is 2.0.2 also.
